format = """
[ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#394260 fg:#a3aed2)\
$directory\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
[](fg:#212736)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#394260"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#212736)]($style)'

[git_status]
style = "bg:#212736"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#212736)]($style)'
